create table appointment
(
    id                     bigint generated by default as identity,
    appointment_date_start timestamp,
    appointment_start_end  timestamp,
    appointment_status     integer,
    customer_id            bigint,
    primary key (id)
)
create table appointment_cosmetic_service
(
    appointment_id      bigint not null,
    cosmetic_service_id bigint not null,
    primary key (appointment_id, cosmetic_service_id)
)
create table cosmetic_service
(
    id    bigint generated by default as identity,
    name  varchar(255),
    price decimal(19, 2),
    primary key (id)
)
create table customer
(
    id           bigint generated by default as identity,
    address      varchar(255),
    email        varchar(255),
    first_name   varchar(255),
    last_name    varchar(255),
    phone_number varchar(255),
    primary key (id)
)
alter table appointment
    add constraint FKmyowslj1th8d9j6j3wlbwrtoe foreign key (customer_id) references customer
alter table appointment_cosmetic_service
    add constraint FKfjkuhpdaisfv7xixj39d28viv foreign key (cosmetic_service_id) references cosmetic_service
alter table appointment_cosmetic_service
    add constraint FKkyb6xppx1dx8ft8rajh6lshks foreign key (appointment_id) references appointment
create table address
(
    id           bigint generated by default as identity,
    house_number integer not null,
    postal_code  integer not null,
    street       varchar(255),
    city_id      bigint,
    customer_id  bigint,
    primary key (id)
)
create table appointment
(
    id                     bigint generated by default as identity,
    appointment_date_start timestamp,
    appointment_start_end  timestamp,
    appointment_status     integer,
    customer_id            bigint,
    primary key (id)
)
create table appointment_cosmetic_service
(
    appointment_id      bigint not null,
    cosmetic_service_id bigint not null,
    primary key (appointment_id, cosmetic_service_id)
)
create table city
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
)
create table cosmetic_service
(
    id    bigint generated by default as identity,
    name  varchar(255),
    price decimal(19, 2),
    primary key (id)
)
create table customer
(
    id           bigint generated by default as identity,
    email        varchar(255),
    first_name   varchar(255),
    last_name    varchar(255),
    phone_number varchar(255),
    address_id   bigint,
    primary key (id)
)
alter table address
    add constraint FKpo044ng5x4gynb291cv24vtea foreign key (city_id) references city
alter table address
    add constraint FK93c3js0e22ll1xlu21nvrhqgg foreign key (customer_id) references customer
alter table appointment
    add constraint FKmyowslj1th8d9j6j3wlbwrtoe foreign key (customer_id) references customer
alter table appointment_cosmetic_service
    add constraint FKfjkuhpdaisfv7xixj39d28viv foreign key (cosmetic_service_id) references cosmetic_service
alter table appointment_cosmetic_service
    add constraint FKkyb6xppx1dx8ft8rajh6lshks foreign key (appointment_id) references appointment
alter table customer
    add constraint FKglkhkmh2vyn790ijs6hiqqpi foreign key (address_id) references address
create table address (id bigint generated by default as identity, house_number integer not null, postal_code integer not null, street varchar(255), city_id bigint, customer_id bigint, primary key (id))
create table appointment (id bigint generated by default as identity, appointment_date_start timestamp, appointment_start_end timestamp, appointment_status integer, customer_id bigint, primary key (id))
create table appointment_cosmetic_service (appointment_id bigint not null, cosmetic_service_id bigint not null, primary key (appointment_id, cosmetic_service_id))
create table city (id bigint generated by default as identity, name varchar(255), primary key (id))
create table cosmetic_service (id bigint generated by default as identity, name varchar(255), price decimal(19,2), primary key (id))
create table customer (id bigint generated by default as identity, email varchar(255), first_name varchar(255), last_name varchar(255), phone_number varchar(255), address_id bigint, primary key (id))
alter table address add constraint FKpo044ng5x4gynb291cv24vtea foreign key (city_id) references city
alter table address add constraint FK93c3js0e22ll1xlu21nvrhqgg foreign key (customer_id) references customer
alter table appointment add constraint FKmyowslj1th8d9j6j3wlbwrtoe foreign key (customer_id) references customer
alter table appointment_cosmetic_service add constraint FKfjkuhpdaisfv7xixj39d28viv foreign key (cosmetic_service_id) references cosmetic_service
alter table appointment_cosmetic_service add constraint FKkyb6xppx1dx8ft8rajh6lshks foreign key (appointment_id) references appointment
alter table customer add constraint FKglkhkmh2vyn790ijs6hiqqpi foreign key (address_id) references address
create table address (id bigint generated by default as identity, house_number integer not null, street varchar(255), city_id bigint, customer_id bigint, primary key (id))
create table appointment (id bigint generated by default as identity, appointment_date_start timestamp, appointment_start_end timestamp, appointment_status integer, customer_id bigint, primary key (id))
create table appointment_cosmetic_service (appointment_id bigint not null, cosmetic_service_id bigint not null, primary key (appointment_id, cosmetic_service_id))
create table city (id bigint generated by default as identity, name varchar(255), postal_code integer not null, primary key (id))
create table cosmetic_service (id bigint generated by default as identity, name varchar(255), price decimal(19,2), primary key (id))
create table customer (id bigint generated by default as identity, email varchar(255), first_name varchar(255), last_name varchar(255), phone_number varchar(255), address_id bigint, primary key (id))
alter table address add constraint FKpo044ng5x4gynb291cv24vtea foreign key (city_id) references city
alter table address add constraint FK93c3js0e22ll1xlu21nvrhqgg foreign key (customer_id) references customer
alter table appointment add constraint FKmyowslj1th8d9j6j3wlbwrtoe foreign key (customer_id) references customer
alter table appointment_cosmetic_service add constraint FKfjkuhpdaisfv7xixj39d28viv foreign key (cosmetic_service_id) references cosmetic_service
alter table appointment_cosmetic_service add constraint FKkyb6xppx1dx8ft8rajh6lshks foreign key (appointment_id) references appointment
alter table customer add constraint FKglkhkmh2vyn790ijs6hiqqpi foreign key (address_id) references address
create table address (id bigint generated by default as identity, house_number integer not null, street varchar(255), city_id bigint, customer_id bigint, primary key (id))
create table appointment (id bigint generated by default as identity, appointment_date_start timestamp, appointment_start_end timestamp, customer_id bigint, primary key (id))
create table appointment_cosmetic_service (appointment_id bigint not null, cosmetic_service_id bigint not null, primary key (appointment_id, cosmetic_service_id))
create table city (id bigint generated by default as identity, name varchar(255), postal_code integer not null, primary key (id))
create table cosmetic_service (id bigint generated by default as identity, name varchar(255), price decimal(19,2), primary key (id))
create table customer (id bigint generated by default as identity, email varchar(255), first_name varchar(255), last_name varchar(255), phone_number varchar(255), address_id bigint, primary key (id))
alter table address add constraint FKpo044ng5x4gynb291cv24vtea foreign key (city_id) references city
alter table address add constraint FK93c3js0e22ll1xlu21nvrhqgg foreign key (customer_id) references customer
alter table appointment add constraint FKmyowslj1th8d9j6j3wlbwrtoe foreign key (customer_id) references customer
alter table appointment_cosmetic_service add constraint FKfjkuhpdaisfv7xixj39d28viv foreign key (cosmetic_service_id) references cosmetic_service
alter table appointment_cosmetic_service add constraint FKkyb6xppx1dx8ft8rajh6lshks foreign key (appointment_id) references appointment
alter table customer add constraint FKglkhkmh2vyn790ijs6hiqqpi foreign key (address_id) references address
create table address (id bigint generated by default as identity, house_number integer not null, street varchar(255), city_id bigint, customer_id bigint, primary key (id))
create table appointment (id bigint generated by default as identity, appointment_date_end timestamp, appointment_date_start timestamp, customer_id bigint, primary key (id))
create table appointment_cosmetic_service (appointment_id bigint not null, cosmetic_service_id bigint not null, primary key (appointment_id, cosmetic_service_id))
create table city (id bigint generated by default as identity, name varchar(255), postal_code integer not null, primary key (id))
create table cosmetic_service (id bigint generated by default as identity, name varchar(255), price decimal(19,2), primary key (id))
create table customer (id bigint generated by default as identity, email varchar(255), first_name varchar(255), last_name varchar(255), phone_number varchar(255), address_id bigint, primary key (id))
alter table address add constraint FKpo044ng5x4gynb291cv24vtea foreign key (city_id) references city
alter table address add constraint FK93c3js0e22ll1xlu21nvrhqgg foreign key (customer_id) references customer
alter table appointment add constraint FKmyowslj1th8d9j6j3wlbwrtoe foreign key (customer_id) references customer
alter table appointment_cosmetic_service add constraint FKfjkuhpdaisfv7xixj39d28viv foreign key (cosmetic_service_id) references cosmetic_service
alter table appointment_cosmetic_service add constraint FKkyb6xppx1dx8ft8rajh6lshks foreign key (appointment_id) references appointment
alter table customer add constraint FKglkhkmh2vyn790ijs6hiqqpi foreign key (address_id) references address
create table address (id bigint generated by default as identity, house_number integer not null, street varchar(255), city_id bigint, customer_id bigint, primary key (id))
create table appointment (id bigint generated by default as identity, appointment_date_end timestamp, appointment_date_start timestamp, customer_id bigint, primary key (id))
create table appointment_cosmetic_service (appointment_id bigint not null, cosmetic_service_id bigint not null, primary key (appointment_id, cosmetic_service_id))
create table city (id bigint generated by default as identity, name varchar(255), postal_code integer not null, primary key (id))
create table cosmetic_service (id bigint generated by default as identity, name varchar(255), price decimal(19,2), primary key (id))
create table customer (id bigint generated by default as identity, email varchar(255), first_name varchar(255), last_name varchar(255), phone_number varchar(255), address_id bigint, primary key (id))
alter table address add constraint FKpo044ng5x4gynb291cv24vtea foreign key (city_id) references city
alter table address add constraint FK93c3js0e22ll1xlu21nvrhqgg foreign key (customer_id) references customer
alter table appointment add constraint FKmyowslj1th8d9j6j3wlbwrtoe foreign key (customer_id) references customer
alter table appointment_cosmetic_service add constraint FKfjkuhpdaisfv7xixj39d28viv foreign key (cosmetic_service_id) references cosmetic_service
alter table appointment_cosmetic_service add constraint FKkyb6xppx1dx8ft8rajh6lshks foreign key (appointment_id) references appointment
alter table customer add constraint FKglkhkmh2vyn790ijs6hiqqpi foreign key (address_id) references address
create table address (id bigint generated by default as identity, house_number integer not null, street varchar(255), city_id bigint, customer_id bigint, primary key (id))
create table appointment (id bigint generated by default as identity, appointment_date_end timestamp, appointment_date_start timestamp, cosmetic_services_id bigint, customer_id bigint, primary key (id))
create table city (id bigint generated by default as identity, name varchar(255), postal_code integer not null, primary key (id))
create table cosmetic_service (id bigint generated by default as identity, name varchar(255), price decimal(19,2), primary key (id))
create table customer (id bigint generated by default as identity, email varchar(255), first_name varchar(255), last_name varchar(255), phone_number varchar(255), address_id bigint, primary key (id))
alter table address add constraint FKpo044ng5x4gynb291cv24vtea foreign key (city_id) references city
alter table address add constraint FK93c3js0e22ll1xlu21nvrhqgg foreign key (customer_id) references customer
alter table appointment add constraint FKr2kphc8mr1008shnsocpnu4lj foreign key (cosmetic_services_id) references cosmetic_service
alter table appointment add constraint FKmyowslj1th8d9j6j3wlbwrtoe foreign key (customer_id) references customer
alter table customer add constraint FKglkhkmh2vyn790ijs6hiqqpi foreign key (address_id) references address
create table address (id bigint generated by default as identity, house_number integer not null, street varchar(255), city_id bigint, customer_id bigint, primary key (id))
create table appointment (id bigint generated by default as identity, appointment_date_end timestamp, appointment_date_start timestamp, cosmetic_services_id bigint, customer_id bigint, primary key (id))
create table city (id bigint generated by default as identity, name varchar(255), postal_code integer not null, primary key (id))
create table cosmetic_service (id bigint generated by default as identity, name varchar(255), price decimal(19,2), primary key (id))
create table customer (id bigint generated by default as identity, email varchar(255), first_name varchar(255), last_name varchar(255), phone_number varchar(255), address_id bigint, primary key (id))
alter table address add constraint FKpo044ng5x4gynb291cv24vtea foreign key (city_id) references city
alter table address add constraint FK93c3js0e22ll1xlu21nvrhqgg foreign key (customer_id) references customer
alter table appointment add constraint FKr2kphc8mr1008shnsocpnu4lj foreign key (cosmetic_services_id) references cosmetic_service
alter table appointment add constraint FKmyowslj1th8d9j6j3wlbwrtoe foreign key (customer_id) references customer
alter table customer add constraint FKglkhkmh2vyn790ijs6hiqqpi foreign key (address_id) references address
create table address (id bigint generated by default as identity, house_number integer not null, street varchar(255), city_id bigint, customer_id bigint, primary key (id))
create table appointment (id bigint generated by default as identity, appointment_date_end timestamp, appointment_date_start timestamp, cosmetic_services_id bigint, customer_id bigint, primary key (id))
create table city (id bigint generated by default as identity, name varchar(255), postal_code integer not null, primary key (id))
create table cosmetic_service (id bigint generated by default as identity, name varchar(255), price decimal(19,2), primary key (id))
create table customer (id bigint generated by default as identity, email varchar(255), first_name varchar(255), last_name varchar(255), phone_number varchar(255), address_id bigint, primary key (id))
alter table address add constraint FKpo044ng5x4gynb291cv24vtea foreign key (city_id) references city
alter table address add constraint FK93c3js0e22ll1xlu21nvrhqgg foreign key (customer_id) references customer
alter table appointment add constraint FKr2kphc8mr1008shnsocpnu4lj foreign key (cosmetic_services_id) references cosmetic_service
alter table appointment add constraint FKmyowslj1th8d9j6j3wlbwrtoe foreign key (customer_id) references customer
alter table customer add constraint FKglkhkmh2vyn790ijs6hiqqpi foreign key (address_id) references address
