create table appointment
(
    id                     bigint generated by default as identity,
    appointment_date_start timestamp,
    appointment_start_end  timestamp,
    appointment_status     integer,
    customer_id            bigint,
    primary key (id)
)
create table appointment_cosmetic_service
(
    appointment_id      bigint not null,
    cosmetic_service_id bigint not null,
    primary key (appointment_id, cosmetic_service_id)
)
create table cosmetic_service
(
    id    bigint generated by default as identity,
    name  varchar(255),
    price decimal(19, 2),
    primary key (id)
)
create table customer
(
    id           bigint generated by default as identity,
    address      varchar(255),
    email        varchar(255),
    first_name   varchar(255),
    last_name    varchar(255),
    phone_number varchar(255),
    primary key (id)
)
alter table appointment
    add constraint FKmyowslj1th8d9j6j3wlbwrtoe foreign key (customer_id) references customer
alter table appointment_cosmetic_service
    add constraint FKfjkuhpdaisfv7xixj39d28viv foreign key (cosmetic_service_id) references cosmetic_service
alter table appointment_cosmetic_service
    add constraint FKkyb6xppx1dx8ft8rajh6lshks foreign key (appointment_id) references appointment
