DROP TABLE IF EXISTS address CASCADE;
CREATE TABLE address
(
    id           bigint generated by default as identity,
    house_number integer not null,
    street       varchar(255),
    city_id      bigint,
    customer_id  bigint,
    primary key (id)
);
DROP TABLE IF EXISTS city CASCADE;
CREATE TABLE city
(
    id   bigint generated by default as identity,
    name varchar(255),
    postal_code  integer not null,
    primary key (id)
);
DROP TABLE IF EXISTS appointment CASCADE;
CREATE TABLE appointment
(
    id                     bigint generated by default as identity,
    appointment_date_start timestamp,
    appointment_start_end  timestamp,
    appointment_status     integer,
    customer_id            bigint,
    primary key (id)
);
DROP TABLE IF EXISTS cosmetic_service CASCADE;
CREATE TABLE cosmetic_service
(
    id    bigint generated by default as identity,
    name  varchar(255),
    price decimal(19, 2),
    primary key (id)
);

DROP TABLE IF EXISTS customer CASCADE;
CREATE TABLE customer
(
    id           bigint generated by default as identity,
    email        varchar(255),
    first_name   varchar(255),
    last_name    varchar(255),
    phone_number varchar(255),
    address_id   bigint,
    primary key (id)
);

DROP TABLE IF EXISTS appointment_cosmetic_service CASCADE;
CREATE TABLE appointment_cosmetic_service
(
    appointment_id      bigint not null,
    cosmetic_service_id bigint not null,
    primary key (appointment_id, cosmetic_service_id)
);


