DROP TABLE IF EXISTS address CASCADE;
CREATE TABLE address
(
    id           bigint generated by default as identity,
    city_id      bigint  NOT NULL,
    street       varchar(255),
    house_number integer not null,
    primary key (id)
);
DROP TABLE IF EXISTS city CASCADE;
CREATE TABLE city
(
    id          bigint generated by default as identity,
    name        varchar(255),
    postal_code integer not null,
    primary key (id)
);
DROP TABLE IF EXISTS appointment CASCADE;
CREATE TABLE appointment
(
    id                     bigint generated by default as identity,
    appointment_date_start timestamp,
    appointment_date_end   timestamp,
    customer_id            bigint NOT NULL,
    primary key (id)
);
DROP TABLE IF EXISTS cosmetic_service CASCADE;
CREATE TABLE cosmetic_service
(
    id      bigint generated by default as identity,
    name    varchar(255),
    price   integer,
    minutes integer,
    primary key (id)
);

DROP TABLE IF EXISTS customer CASCADE;
CREATE TABLE customer
(
    id           bigint generated by default as identity,
    first_name   varchar(255),
    last_name    varchar(255),
    address_id   bigint NOT NULL,
    phone_number varchar(255),
    email        varchar(255),
    primary key (id)
);

DROP TABLE IF EXISTS appointment_cosmetic_service CASCADE;
CREATE TABLE appointment_cosmetic_service
(
    appointment_id      bigint not null,
    cosmetic_service_id bigint not null,
    FOREIGN KEY (appointment_id) REFERENCES appointment (id),
    FOREIGN KEY (cosmetic_service_id) REFERENCES cosmetic_service (id)
);

